{"vulnerability": "Stack-based Buffer Overflow", "affecting": "Affecting cetic/6lbr package, versions [0,]", "severity score": "7.5", "severity level": "high", "id": "https://security.snyk.io/vuln/SNYK-UNMANAGED-CETIC6LBR-6141024", "fix": "There is no fixed version for cetic/6lbr ."}
{"vulnerability": "Improper Handling of Unicode Encoding", "affecting": "Affecting github.com/ewen-lbh/ffcss package, versions *", "severity score": "5.3", "severity level": "medium", "id": "https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMEWENLBHFFCSS-6140433", "fix": "A fix was pushed into the master branch but not yet published."}
{"vulnerability": "Open Redirect", "affecting": "Affecting flask-security package, versions [0,]", "severity score": "5.4", "severity level": "medium", "id": "https://security.snyk.io/vuln/SNYK-PYTHON-FLASKSECURITY-6140501", "fix": "There is no fixed version for Flask-Security ."}
{"vulnerability": "Improper Handling of Insufficient Privileges", "affecting": "Affecting wrangler package, versions >=2.0.0 <2.20.2 >=3.0.0 <3.19.0", "severity score": "8.5", "severity level": "high", "id": "https://security.snyk.io/vuln/SNYK-JS-WRANGLER-6140500", "fix": "Upgrade wrangler to version 2.20.2, 3.19.0 or higher."}
{"vulnerability": "Arbitrary File Read", "affecting": "Affecting wrangler package, versions >=3.9.0 <3.18.0", "severity score": "6.4", "severity level": "medium", "id": "https://security.snyk.io/vuln/SNYK-JS-WRANGLER-6140498", "fix": "Upgrade wrangler to version 3.18.0 or higher."}
{"vulnerability": "SQL Injection", "affecting": "Affecting org.jeecgframework.jimureport:jimureport-spring-boot-starter package, versions [0,]", "severity score": "9.8", "severity level": "critical", "id": "https://security.snyk.io/vuln/SNYK-JAVA-ORGJEECGFRAMEWORKJIMUREPORT-6140760", "fix": "There is no fixed version for org.jeecgframework.jimureport:jimureport-spring-boot-starter ."}
{"vulnerability": "SQL Injection", "affecting": "Affecting net.mingsoft:ms-mcms package, versions [0,]", "severity score": "9.8", "severity level": "critical", "id": "https://security.snyk.io/vuln/SNYK-JAVA-NETMINGSOFT-6140759", "fix": "There is no fixed version for net.mingsoft:ms-mcms ."}
{"vulnerability": "Server-Side Request Forgery (SSRF)", "affecting": "Affecting miniflare package, versions >=3.20230821.0 <3.20231030.2", "severity score": "8", "severity level": "high", "id": "https://security.snyk.io/vuln/SNYK-JS-MINIFLARE-6140499", "fix": "Upgrade miniflare to version 3.20231030.2 or higher."}
{"vulnerability": "Arbitrary Code Execution", "affecting": "Affecting org.jeasy:easy-rules-mvel package, versions [0,]", "severity score": "8.1", "severity level": "high", "id": "https://security.snyk.io/vuln/SNYK-JAVA-ORGJEASY-6140756", "fix": "There is no fixed version for org.jeasy:easy-rules-mvel ."}
{"vulnerability": "Malicious Package", "affecting": "Affecting sd-v13.js package, versions *", "severity score": "9.8", "severity level": "critical", "id": "https://security.snyk.io/vuln/SNYK-JS-SDV13JS-6140423", "fix": "Avoid using all malicious instances of the sd-v13.js package."}
{"vulnerability": "Malicious Package", "affecting": "Affecting discord.js-selfbots-v13 package, versions *", "severity score": "9.8", "severity level": "critical", "id": "https://security.snyk.io/vuln/SNYK-JS-DISCORDJSSELFBOTSV13-6140424", "fix": "Avoid using all malicious instances of the discord.js-selfbots-v13 package."}
{"vulnerability": "Insufficient Entropy", "affecting": "Affecting github.com/pubnub/swift package, versions <6.2.0", "severity score": "5.9", "severity level": "medium", "id": "https://security.snyk.io/vuln/SNYK-SWIFT-PUBNUBSWIFT-6098381", "fix": "Upgrade pubnub/swift to version 6.2.0 or higher."}
{"vulnerability": "Insufficient Entropy", "affecting": "Affecting pubnub package, versions <5.2.0", "severity score": "5.9", "severity level": "medium", "id": "https://security.snyk.io/vuln/SNYK-COCOAPODS-PUBNUB-6098384", "fix": "Upgrade PubNub to version 5.2.0 or higher."}
{"vulnerability": "Insufficient Entropy", "affecting": "Affecting pubnub package, versions <4.3.0", "severity score": "5.9", "severity level": "medium", "id": "https://security.snyk.io/vuln/SNYK-PUB-PUBNUB-6098385", "fix": "Upgrade pubnub to version 4.3.0 or higher."}
{"vulnerability": "Arbitrary File Upload", "affecting": "Affecting net.mingsoft:ms-mcms package, versions [0,]", "severity score": "8.1", "severity level": "high", "id": "https://security.snyk.io/vuln/SNYK-JAVA-NETMINGSOFT-2385690", "fix": "There is no fixed version for net.mingsoft:ms-mcms ."}
{"vulnerability": "Prototype Pollution", "affecting": "Affecting mockjs package, versions *", "severity score": "8.2", "severity level": "high", "id": "https://security.snyk.io/vuln/SNYK-JS-MOCKJS-6051365", "fix": "There is no fixed version for mockjs ."}
{"vulnerability": "Insufficient Entropy", "affecting": "Affecting pubnub package, versions [,7.3.0)", "severity score": "5.9", "severity level": "medium", "id": "https://security.snyk.io/vuln/SNYK-PYTHON-PUBNUB-6098375", "fix": "Upgrade pubnub to version 7.3.0 or higher."}
{"vulnerability": "Insufficient Entropy", "affecting": "Affecting pubnub/pubnub package, versions <6.1.0", "severity score": "5.9", "severity level": "medium", "id": "https://security.snyk.io/vuln/SNYK-PHP-PUBNUBPUBNUB-6098376", "fix": "Upgrade pubnub/pubnub to version 6.1.0 or higher."}
{"vulnerability": "Insufficient Entropy", "affecting": "Affecting pubnub package, versions <5.3.0", "severity score": "5.9", "severity level": "medium", "id": "https://security.snyk.io/vuln/SNYK-RUBY-PUBNUB-6098377", "fix": "Upgrade pubnub to version 5.3.0 or higher."}
{"vulnerability": "Plaintext Storage of a Password", "affecting": "Affecting shadow-maint/shadow package, versions [,4.14.0-rc1)", "severity score": "4.7", "severity level": "medium", "id": "https://security.snyk.io/vuln/SNYK-UNMANAGED-SHADOWMAINTSHADOW-6140326", "fix": "Upgrade shadow-maint/shadow to version 4.14.0-rc1 or higher."}
{"vulnerability": "Inadequate Encryption Strength", "affecting": "Affecting blinksocks package, versions *", "severity score": "5.3", "severity level": "medium", "id": "https://security.snyk.io/vuln/SNYK-JS-BLINKSOCKS-6137728", "fix": "There is no fixed version for blinksocks ."}
{"vulnerability": "Use After Free", "affecting": "Affecting electron package, versions <26.6.3 >=27.0.0 <27.2.0", "severity score": "7.1", "severity level": "high", "id": "https://security.snyk.io/vuln/SNYK-JS-ELECTRON-6105391", "fix": "Upgrade electron to version 26.6.3, 27.2.0 or higher."}
{"vulnerability": "Heap-based Buffer Overflow", "affecting": "Affecting electron package, versions <26.6.3 >=27.0.0 <27.2.0 >=28.0.0 <28.1.0", "severity score": "7.3", "severity level": "high", "id": "https://security.snyk.io/vuln/SNYK-JS-ELECTRON-6137744", "fix": "Upgrade electron to version 26.6.3, 27.2.0, 28.1.0 or higher."}
{"vulnerability": "Malicious Package", "affecting": "Affecting element-block-starter package, versions *", "severity score": "9.8", "severity level": "critical", "id": "https://security.snyk.io/vuln/SNYK-JS-ELEMENTBLOCKSTARTER-6137915", "fix": "Avoid using all malicious instances of the element-block-starter package."}
{"vulnerability": "Malicious Package", "affecting": "Affecting jupyter_matlab_labextension package, versions *", "severity score": "9.8", "severity level": "critical", "id": "https://security.snyk.io/vuln/SNYK-JS-JUPYTERMATLABLABEXTENSION-6137914", "fix": "Avoid using all malicious instances of the jupyter_matlab_labextension package."}
{"vulnerability": "Malicious Package", "affecting": "Affecting release-management-slack package, versions *", "severity score": "9.8", "severity level": "critical", "id": "https://security.snyk.io/vuln/SNYK-JS-RELEASEMANAGEMENTSLACK-6137916", "fix": "Avoid using all malicious instances of the release-management-slack package."}
{"vulnerability": "Denial of Service (DoS)", "affecting": "Affecting sidekiq package, versions <6.5.10 >=7.0.0, <7.1.3", "severity score": "4.9", "severity level": "medium", "id": "https://security.snyk.io/vuln/SNYK-RUBY-SIDEKIQ-5885107", "fix": "Upgrade sidekiq to version 6.5.10, 7.1.3 or higher."}
{"vulnerability": "Arbitrary Argument Injection", "affecting": "Affecting blamer package, versions <1.0.4", "severity score": "6.5", "severity level": "medium", "id": "https://security.snyk.io/vuln/SNYK-JS-BLAMER-5731318", "fix": "Upgrade blamer to version 1.0.4 or higher."}
{"vulnerability": "Use After Free", "affecting": "Affecting electron package, versions >=22.0.0 <22.3.6 >=23.0.0 <23.2.3", "severity score": "7.5", "severity level": "high", "id": "https://security.snyk.io/vuln/SNYK-JS-ELECTRON-5425842", "fix": "Upgrade electron to version 22.3.6, 23.2.3 or higher."}
{"vulnerability": "Command Injection", "affecting": "Affecting pydash package, versions [,6.0.0)", "severity score": "7.4", "severity level": "high", "id": "https://security.snyk.io/vuln/SNYK-PYTHON-PYDASH-5916518", "fix": "Upgrade pydash to version 6.0.0 or higher."}
{"vulnerability": "Malicious Package", "affecting": "Affecting react-persian-calendar-date-picker222 package, versions *", "severity score": "9.8", "severity level": "critical", "id": "https://security.snyk.io/vuln/SNYK-JS-REACTPERSIANCALENDARDATEPICKER222-6129057", "fix": "Avoid using all malicious instances of the react-persian-calendar-date-picker222 package."}
{"vulnerability": "Denial of Service (DoS)", "affecting": "Affecting graphql package, versions >=16.3.0 <16.8.1", "severity score": "5.3", "severity level": "medium", "id": "https://security.snyk.io/vuln/SNYK-JS-GRAPHQL-5905181", "fix": "Upgrade graphql to version 16.8.1 or higher."}
{"vulnerability": "Out-of-bounds Read", "affecting": "Affecting electron package, versions >=12.0.0 <12.2.3 >=13.0.0 <13.6.1 >=14.0.0 <14.2.1 >=15.0.0 <15.3.1", "severity score": "8.8", "severity level": "high", "id": "https://security.snyk.io/vuln/SNYK-JS-ELECTRON-1932545", "fix": "Upgrade electron to version 12.2.3, 13.6.1, 14.2.1, 15.3.1 or higher."}
{"vulnerability": "Use After Free", "affecting": "Affecting electron package, versions <6.1.10 >=7.0.0 <7.2.2 >=8.0.0 <8.2.0", "severity score": "8.8", "severity level": "high", "id": "https://security.snyk.io/vuln/SNYK-JS-ELECTRON-565571", "fix": "Upgrade electron to version 6.1.10, 7.2.2, 8.2.0 or higher."}
{"vulnerability": "Use After Free", "affecting": "Affecting electron package, versions >=6.0.0 <6.1.12 >=7.0.0 <7.3.0 >=8.0.0 <8.3.0", "severity score": "8.8", "severity level": "high", "id": "https://security.snyk.io/vuln/SNYK-JS-ELECTRON-569099", "fix": "Upgrade electron to version 6.1.12, 7.3.0, 8.3.0 or higher."}
{"vulnerability": "Use After Free", "affecting": "Affecting electron package, versions >=6.0.0 <6.1.12 >=7.0.0 <7.3.0", "severity score": "9.6", "severity level": "critical", "id": "https://security.snyk.io/vuln/SNYK-JS-ELECTRON-569109", "fix": "Upgrade electron to version 6.1.12, 7.3.0 or higher."}
{"vulnerability": "Regular Expression Denial of Service (ReDoS)", "affecting": "Affecting semver package, versions <5.7.2 >=6.0.0 <6.3.1 >=7.0.0 <7.5.2", "severity score": "7.5", "severity level": "high", "id": "https://security.snyk.io/vuln/SNYK-JS-SEMVER-3247795", "fix": "Upgrade semver to version 5.7.2, 6.3.1, 7.5.2 or higher."}
{"vulnerability": "XML External Entity (XXE) Injection", "affecting": "Affecting ch.qos.reload4j:reload4j package, versions [,1.2.22)", "severity score": "7.3", "severity level": "high", "id": "https://security.snyk.io/vuln/SNYK-JAVA-CHQOSRELOAD4J-5731326", "fix": "Upgrade ch.qos.reload4j:reload4j to version 1.2.22 or higher."}
{"vulnerability": "Deserialization of Untrusted Data", "affecting": "Affecting org.clojure:clojure package, versions [1.2.0,1.9.0)", "severity score": "6.6", "severity level": "medium", "id": "https://security.snyk.io/vuln/SNYK-JAVA-ORGCLOJURE-5740378", "fix": "Upgrade org.clojure:clojure to version 1.9.0 or higher."}
{"vulnerability": "Command Injection", "affecting": "Affecting git-commit-info package, versions <2.0.2", "severity score": "9.8", "severity level": "critical", "id": "https://security.snyk.io/vuln/SNYK-JS-GITCOMMITINFO-5740174", "fix": "Upgrade git-commit-info to version 2.0.2 or higher."}
{"vulnerability": "Prototype Pollution", "affecting": "Affecting flatnest package, versions *", "severity score": "7.3", "severity level": "high", "id": "https://security.snyk.io/vuln/SNYK-JS-FLATNEST-3185149", "fix": "A fix was pushed into the master branch but not yet published."}
{"vulnerability": "Improper Interaction Between Multiple Correctly-Behaving Entities", "affecting": "Affecting darcyclarke-manifest-pkg package, versions *", "severity score": "3.7", "severity level": "low", "id": "https://security.snyk.io/vuln/SNYK-JS-DARCYCLARKEMANIFESTPKG-5742970", "fix": "There is no fixed version for darcyclarke-manifest-pkg ."}
{"vulnerability": "Prototype Pollution", "affecting": "Affecting underscore-keypath package, versions >=0.0.11", "severity score": "7.5", "severity level": "high", "id": "https://security.snyk.io/vuln/SNYK-JS-UNDERSCOREKEYPATH-5416714", "fix": "There is no fixed version for underscore-keypath ."}
{"vulnerability": "Heap-based Buffer Overflow", "affecting": "Affecting webmproject/libwebp package, versions [0.5.0,1.3.2)", "severity score": "10", "severity level": "critical", "id": "https://security.snyk.io/vuln/SNYK-UNMANAGED-WEBMPROJECTLIBWEBP-5918283", "fix": "Upgrade webmproject/libwebp to version 1.3.2 or higher."}
{"vulnerability": "Prototype Pollution", "affecting": "Affecting tough-cookie package, versions <4.1.3", "severity score": "6.5", "severity level": "medium", "id": "https://security.snyk.io/vuln/SNYK-JS-TOUGHCOOKIE-5672873", "fix": "Upgrade tough-cookie to version 4.1.3 or higher."}
